### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by thornecc** [udacity/mws-restaurant-stage-1#133]
I want to specify a license on my downstream MWS restaurant project, but can't since I don't know how the original code is licensed. Would it be possible to add an appropriate open source license to this project?

**Comment by binary-idiot** [comment]
I'd love to know how the project is licensed , I want to make my final project live but I dont want to worry about any legal issues

**Comment by hbkwong** [comment]
Please review the section of the [Terms of Use](https://www.udacity.com/legal/terms-of-use) titled _LICENSE TO EDUCATIONAL CONTENT_
