### ISSUE TITLE
Google Maps API token is leaked

### ISSUE THREAD

**Issue by d0nutptr** [udacity/mws-restaurant-stage-1#4]
You have a valid Google Maps API token still in your git history (see: https://github.com/udacity/mws-restaurant-stage-1/commit/3b408251faef201503c04c71611fcec132b0bc31).

I recommend two courses of action:

1. Invalidate the API token (this is a must)
2. Scrub the git history (not a big deal especially if you do step 1).

As far as I can tell, the API key is still valid.

**Comment by jarmenz** [comment]
Agree with @d0nutptr, **line 64** in **restaurant.html**.

**Comment by ThisNameWasTaken** [comment]
@d0nutptr and @avilde  and what would the problem be? If you look at this example on [w3schools](https://www.w3schools.com/graphics/google_maps_intro.asp) when you inspect the page you can see their API key. How is that an issue?

**Comment by avilde** [comment]
@ThisNameWasTaken, have you read the the Terms of Service from Google Maps API? By inspecting the page sure you will get the API key but it is **illegal** to re-use other developer's key.

Even w3schools have example link written like this:
<script src="https://maps.googleapis.com/maps/api/js?key=**YOUR_KEY**&callback=myMap"></script>

Google Maps API ToS:
**5.2. Your Passwords and Account Security.**
"You must notify Google immediately if you become aware of any unauthorized use of your password; your Google Account; or any unique identifier that Google requires you to use, such as an **API Key** or **client ID** (a "Developer Identifier")."

**Comment by d0nutptr** [comment]
Actually, my bad @ThisNameWasTaken . I looked into it a little more and I see that Google provides 2 kinds of API keys for this exact purpose :)

@avilde Look at the page source.
