### ISSUE TITLE
'python3' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Asim1996** [udacity/mws-restaurant-stage-1#73]
For starting server use: py -3 -m http.server 8000 instead of python3 -m http.server 8000 as it gives an error.

**Comment by forbiddenvoid** [comment]
That's going to be environment specific. If you've aliased Python 3 differently it won't work, but most implementations of Python 3 should work with `python3`

**Comment by emydame** [comment]
Remove the 3 and use just Python, if you're sure you have added Python to your environment path
