### ISSUE TITLE
all requests are done inside the same host

### ISSUE THREAD

**Issue by amrnt** [udacity/mws-restaurant-stage-1#9]
Wouldn't be better to change the code below to: (since everything thing is being requested within the same host).

```js
 static get DATABASE_URL() { 
   return `/data/restaurants.json`; 
 } 
```

https://github.com/udacity/mws-restaurant-stage-1/blob/7faf9bb8c8152032db8b0ca35c8dda48ece7fd03/js/dbhelper.js#L10-L13

**Comment by forbiddenvoid** [comment]
This is addressed with the server provided in stage 2.
